services:
  - type: web
    name: fightback
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: VITE_PUBLIC_URL
        sync: false
      - key: VITE_API_URL
        sync: false